### ISSUE TITLE
"Sensory Microbooster" speeds up time

### ISSUE THREAD

**Issue by AsteriskDelta** [Dmgvol/Ghostrunner-Mods#2]
(I've played three rounds of the modded waves, and this is the first time I've seen the issue, so I'm not sure as to its reproducibility)
Shortly after a kill, instead of time "slowing" and you having more time to react and pick your next target, it instead massively increases your speed while the enemies remain in normal time. This is especially pronounced if you "dash" during one of these boosts, as it basically catapults you across the map.
It's interesting to note that the distance traveled with the "speed boost" is about the same as how far you could run while under the effect of Sensory Microbooster-- ie, it seems like the same constants are being applied, just increasing the player's timescale instead of decreasing the global timescale.

Never observed this bug in stock Ghostrunner, and I've played hundreds of wave rounds.

Mods active at the time:
- GhostMod (N/A)
- MovementMod (inactive? No wave-related settings I'm aware of)
- Trainer (inactive)
- Unlocker (N/A)
- WaveMod
Not sure which mod is causing this, but I've now disabled MovementMod, Trainer, and Unlocker-- I'll update the issue if I encounter the bug again.

**Comment by Dmgvol** [comment]
The only mod that alters game dilation(speed) is the Trainer, try running the WaveMod without any other mods installed.

Also, if you have any further bugs/issues, please mention them in Discord.
