### ISSUE TITLE
WaveMod "Classic" map's fall/death colliders are too high

### ISSUE THREAD

**Issue by AsteriskDelta** [Dmgvol/Ghostrunner-Mods#3]
The death colliders appear to trigger the moment you go lower than the floor (perhaps this is simply the default layout that shipped, and was never updated for the new map?). This may be a matter of personal preference, but I'll list the reasons I think this should be changed:
- This makes going for a ledge grip (in the new portion of the map, where ledges are floor-level) suicide, which is an established mechanic throughout the game.
- If you're maneuvering during a sensory boost, you can sink below the "death line" even when you could have reached the platform just fine
- It kills you even when it's entirely possible to recover via a grapple point or boost

**Comment by Dmgvol** [comment]
The death collider is already lower by a lot than the default height, the collider is under the water surface. 

If you have any additional issues/bugs, please mention them in the Discord instead of Github Issues.
